# Generated by Django 4.2 on 2024-04-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='چرا مشتریان باید خدمات ما را انتخاب کنند؟', max_length=150, verbose_name='خصوصیت شرکت')),
                ('icon_svg_code', models.CharField(help_text='یک کد svg را درون این باکس قرار دهید', max_length=1000, verbose_name='آیکون')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل شرکت')),
                ('phone', models.CharField(max_length=11, verbose_name='موبایل شرکت')),
                ('tel', models.CharField(max_length=11, verbose_name='تلفن شرکت')),
                ('about_company', models.TextField(max_length=1000, verbose_name='توضیح و معرفی شرکت')),
                ('office_addres', models.CharField(max_length=500, verbose_name='ادرس محل دفتر')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(help_text='عنوان خدمتی که رائه میکنید را وارد کنید', max_length=75, unique=True)),
                ('icon_svg_code', models.CharField(help_text='یک کد svg را درون این باکس قرار دهید', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام شرکتی که با شما همکاری کرده است را بنویسید', max_length=75, unique=True)),
                ('logo', models.ImageField(help_text='یک تصویر برای لوگوی شرکتی که مشتری شما بوده است انتخاب کنید', upload_to='uploads/customer_logos/')),
            ],
        ),
    ]
