# Generated by Django 4.2 on 2024-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/', verbose_name='ویدیوی معرفی'),
        ),
    ]
