# Generated by Django 5.0.6 on 2024-07-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_companyattribute_icon_svg_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'متن اینترو صفحه اصلی', 'verbose_name_plural': 'متن اینترو صفحه اصلی'},
        ),
    ]
