# Generated by Django 4.2 on 2024-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_companyinfo_instagram_companyinfo_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoldCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام شرکتی که با شما همکاری کرده است را بنویسید', max_length=75, unique=True, verbose_name='نام/عنوان')),
                ('logo', models.ImageField(help_text='یک تصویر برای لوگوی شرکتی که مشتری شما بوده است انتخاب کنید', upload_to='uploads/customer_logos/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'مشتریان برجسته',
                'verbose_name_plural': 'مشتریان برجسته',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterModelOptions(
            name='companyattribute',
            options={'verbose_name': 'مشتریان چرا باید شرکت ما را انتخاب کنند؟', 'verbose_name_plural': 'مشتریان چرا باید شرکت ما را انتخاب کنند؟'},
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'اطلاعات تماس شرکت', 'verbose_name_plural': 'اطلاعات تماس شرکت'},
        ),
        migrations.AlterModelOptions(
            name='companyservice',
            options={'verbose_name': 'خدمات/سرویس ها', 'verbose_name_plural': 'خدمات/سرویس ها'},
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='service_title',
            field=models.CharField(help_text='عنوان خدمتی که رائه میکنید را وارد کنید', max_length=75, unique=True, verbose_name='عنوان خدمت (سرویس)'),
        ),
    ]
