# Generated by Django 4.2 on 2024-04-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_boldcustomer_delete_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام شرکت'),
            preserve_default=False,
        ),
    ]
