# Generated by Django 4.2 on 2024-04-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_app', '0002_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
