# Generated by Django 4.2 on 2024-04-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_app', '0005_alter_contact_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': ' فرم ثبت درخواست های کاربر', 'verbose_name_plural': 'فرم های ثبت درخواست کاربران'},
        ),
        migrations.AlterModelOptions(
            name='counseling',
            options={'verbose_name': 'مشاوره', 'verbose_name_plural': 'انواع مشاوره ها'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='counseling_type',
            field=models.OneToOneField(help_text='نوع مشاوره ای که کاربر در فرمی که در صفحه مشاوره است ثبت کرده. ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counseling_app.counseling', verbose_name='نوع مشاوره درخواستی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت فرم درخواست'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='نام کسی که فرم ثبت درخواست  در صفحه مشاوره را ثبت کرده است', max_length=60, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_phone',
            field=models.CharField(max_length=11, verbose_name='موبایل کاربر'),
        ),
    ]
