# Generated by Django 4.2 on 2024-04-24 16:20

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_app', '0006_alter_contact_options_alter_counseling_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
