# Generated by Django 4.2 on 2024-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapny_name', models.CharField(max_length=75, verbose_name='نام شرکت')),
                ('description_about_company', models.TextField(max_length=1500, verbose_name='درباره شرکت')),
                ('boss_name', models.CharField(max_length=75, verbose_name='نام و نام خانوادگی رییس ')),
                ('description_about_boss', models.TextField(max_length=1500, verbose_name='درباره رییس شرکت')),
                ('picture_about_boss', models.ImageField(upload_to='uploads/customer_logos/', verbose_name='تصویر مالک یا رییس شرکت')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل شرکت')),
                ('phone', models.CharField(max_length=11, verbose_name='موبایل شرکت')),
                ('tel', models.CharField(max_length=11, verbose_name='تلفن شرکت')),
                ('office_addres', models.CharField(max_length=500, verbose_name='ادرس محل دفتر')),
                ('instagram', models.CharField(max_length=50, verbose_name='نام کاربری اکانت اینستاگرام')),
                ('telegram', models.CharField(max_length=50, verbose_name='آی دی کانال یا چت تلگرام')),
            ],
            options={
                'verbose_name': 'توضیحات درباره شرکت و رئیس',
                'verbose_name_plural': 'توضیحات درباره شرکت و رئیس',
            },
        ),
        migrations.CreateModel(
            name='FrequentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500, unique=True, verbose_name='پرسش')),
                ('answer', models.TextField(max_length=1500, verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'پرسش های پرتکرار',
                'verbose_name_plural': 'پرسش های پرتکرار',
            },
        ),
    ]
