# Generated by Django 4.2 on 2024-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapny_name', models.CharField(max_length=75, verbose_name='نام شرکت')),
                ('description_about_company', models.TextField(max_length=1500, verbose_name='درباره شرکت')),
                ('boss_name', models.CharField(max_length=75, verbose_name='نام و نام خانوادگی رییس ')),
                ('description_about_boss', models.TextField(max_length=1500, verbose_name='درباره رییس شرکت')),
                ('picture_about_boss', models.ImageField(upload_to='uploads/customer_logos/', verbose_name='تصویر مالک یا رییس شرکت')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500, unique=True)),
                ('answer', models.TextField(max_length=1500)),
            ],
        ),
    ]
