# Generated by Django 4.2 on 2024-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'verbose_name': 'توضیحات درباره شرکت و رئیس', 'verbose_name_plural': 'توضیحات درباره شرکت و رئیس'},
        ),
        migrations.AlterModelOptions(
            name='frequentquestion',
            options={'verbose_name': 'پرسش های پرتکرار', 'verbose_name_plural': 'پرسش های پرتکرار'},
        ),
        migrations.AlterField(
            model_name='frequentquestion',
            name='answer',
            field=models.TextField(max_length=1500, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='frequentquestion',
            name='question',
            field=models.TextField(max_length=500, unique=True, verbose_name='پرسش'),
        ),
    ]
