# Generated by Django 5.0.6 on 2024-07-05 08:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_alter_frequentquestion_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'verbose_name': 'توضیحات درباره شرکت و رئیس و اطلاعات تماس', 'verbose_name_plural': 'توضیحات درباره شرکت و رئیس و اطلاعات تماس'},
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='description_about_boss',
            field=ckeditor.fields.RichTextField(max_length=1500, verbose_name='درباره رییس شرکت'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='description_about_company',
            field=ckeditor.fields.RichTextField(max_length=1500, verbose_name='درباره شرکت'),
        ),
        migrations.AlterField(
            model_name='frequentquestion',
            name='answer',
            field=ckeditor.fields.RichTextField(max_length=1500, verbose_name='پاسخ'),
        ),
    ]
